### PR TITLE
Feature/add window group tests

### PR DESCRIPTION
**Pull request by orensig**
This PR includes a new class in the tests' DSL that corresponds with Label Summary in pyspark-runner. It aims to enable users to perform tests on Label Summary's output, namely the agreement level metrics of the dataset (Fleiss/Cohen's kappa, average agreement level and median agreement level).

### CODE REVIEW

**Review by estiller — CHANGES_REQUESTED** [review]
According to PEP8, shouldn't the `Labels` package be named `labels` and the `labels.py` module be named `label_summary.py`?
I see that some of the other packages in the module have the same issue, and I'm not sure if it is better to align with them or change their naming to match the standard.

Also, there are no tests for this feature. How do we know this works and what is the expected usage? Is it possible to add a couple?

@roadan, what do you think about these issues?

**Comment by estiller** [comment]
@orensig - also, please add a description to the PR stating what it changes/adds. Thanks!

**Comment by orensig** [comment]
> According to PEP8, shouldn't the `Labels` package be named `labels` and the `labels.py` module be named `label_summary.py`? I see that some of the other packages in `badook-tests-python` have the same issue, and I'm not sure if it is better to align with them or change their naming to match the standard.
> 
> Also, there are no tests for this feature. How do we know this works and what is the expected usage? Is it possible to add a couple?
> 
> @roadan, what do you think about these issues?

@estiller The tests are in another repo: https://github.com/badook-ai/test_scripts

**Comment by estiller** [comment]
> @estiller The tests are in another repo: https://github.com/badook-ai/test_scripts

Unfortunately, we can't rely on that as we need to have unit tests that run here as part of the CI when we commit new items.

**Comment by estiller** [comment]
@orensig please note that this package is still `prerelease` so the label should be `semver:prerelease`. I just changed it.

**Review by estiller — COMMENTED** [review]
I think we still need to add some tests here. Please talk with @roadan and whatever he approves is fine by me.

**Review by roadan — APPROVED** [review]

**Pull request merged**
